---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readr)
library(car)
library(emmeans)
library(tables)
library(RcmdrMisc)
library(dplyr)


dd <- read_csv("train.csv")
dd$dist <- sqrt(dd$x^2 + dd$y^2 + dd$z^2)
dd$epoch <- as.numeric(as.POSIXct(dd$epoch))
dd$first <- min(dd$epoch)
dd$epoch <- dd$epoch - min(dd$epoch)
head(dd)

```


```{r}
write(toString(dd$first[1]), file = "mixedfull_betas.txt", append=TRUE)  

for(i in 0:599){
    print(i)
    
    ddi <- filter(dd, sat_id==i)
    t <- (ddi$epoch[25]-ddi$epoch[1])
    
    write(toString(t), file = "mixedfull_betas.txt", append=TRUE)  
    
     lmX <- lm(x ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmY <- lm(y ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmZ <- lm(z ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)

 lmVx <- lm(Vx ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmVy <- lm(Vy ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmVz <- lm(Vz ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
      
     write(toString(summary(lmX)$coefficients[,1]), file = "mixedfull_betas.txt", append=TRUE)
     write(toString(summary(lmY)$coefficients[,1]), file = "mixedfull_betas.txt", append=TRUE)
     write(toString(summary(lmZ)$coefficients[,1]), file = "mixedfull_betas.txt", append=TRUE)
     write(toString(summary(lmVx)$coefficients[,1]), file = "mixedfull_betas.txt", append=TRUE)
     write(toString(summary(lmVy)$coefficients[,1]), file = "mixedfull_betas.txt", append=TRUE)
     write(toString(summary(lmVz)$coefficients[,1]), file = "mixedfull_betas.txt", append=TRUE)
}
```

