---
title: "Make_timefull"
output: html_notebook
---


```{r}
library(readr)
library(car)
library(emmeans)
library(tables)
library(RcmdrMisc)
library(dplyr)

dd <- read_csv("../data/train.csv")
dd$epoch <- as.numeric(as.POSIXct(dd$epoch))
dd$first <- min(dd$epoch)
dd$epoch <- dd$epoch - min(dd$epoch)
head(dd)
```


Read periods
```{r}
TT <- read_csv("../data/periods.csv")
```


Generate periods -- put them int txt format
```{r}
for(i in 0:599){
  for (j in 1:6){
    write(toString(TT[i+1,j]), file = "periods.txt", append=TRUE)
  }
}

```

Generate coefs
```{r}
write(toString(dd$first[1]), file = "mixedfullperiods_betas.txt", append=TRUE)  

for(i in 0:599){
    print(i)
    
    ddi <- filter(dd, sat_id==i)
    
    t1 <- unlist(TT[i+1,1])
    t2 <- unlist(TT[i+1,2])
    t3 <- unlist(TT[i+1,3])
    t4 <- unlist(TT[i+1,4])
    t5 <- unlist(TT[i+1,5])
    t6 <- unlist(TT[i+1,6])
    
    lmX <- lm(x ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmY <- lm(y ~ epoch*sin(2*pi/t2*epoch)+epoch*cos(2*pi/t2*epoch)+epoch*sin(4*pi/t2*epoch)+epoch*cos(4*pi/t2*epoch)+epoch*sin(6*pi/t2*epoch)+epoch*cos(6*pi/t2*epoch)+epoch*sin(8*pi/t2*epoch)+epoch*cos(8*pi/t2*epoch)+epoch*sin(10*pi/t2*epoch)+epoch*cos(10*pi/t2*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmZ <- lm(z ~ epoch*sin(2*pi/t3*epoch)+epoch*cos(2*pi/t3*epoch)+epoch*sin(4*pi/t3*epoch)+epoch*cos(4*pi/t3*epoch)+epoch*sin(6*pi/t3*epoch)+epoch*cos(6*pi/t3*epoch)+epoch*sin(8*pi/t3*epoch)+epoch*cos(8*pi/t3*epoch)+epoch*sin(10*pi/t3*epoch)+epoch*cos(10*pi/t3*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)

 lmVx <- lm(Vx ~ epoch*sin(2*pi/t4*epoch)+epoch*cos(2*pi/t4*epoch)+epoch*sin(4*pi/t4*epoch)+epoch*cos(4*pi/t4*epoch)+epoch*sin(6*pi/t4*epoch)+epoch*cos(6*pi/t4*epoch)+epoch*sin(8*pi/t4*epoch)+epoch*cos(8*pi/t4*epoch)+epoch*sin(10*pi/t4*epoch)+epoch*cos(10*pi/t4*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmVy <- lm(Vy ~ epoch*sin(2*pi/t5*epoch)+epoch*cos(2*pi/t5*epoch)+epoch*sin(4*pi/t5*epoch)+epoch*cos(4*pi/t5*epoch)+epoch*sin(6*pi/t5*epoch)+epoch*cos(6*pi/t5*epoch)+epoch*sin(8*pi/t5*epoch)+epoch*cos(8*pi/t5*epoch)+epoch*sin(10*pi/t5*epoch)+epoch*cos(10*pi/t5*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmVz <- lm(Vz ~ epoch*sin(2*pi/t6*epoch)+epoch*cos(2*pi/t6*epoch)+epoch*sin(4*pi/t6*epoch)+epoch*cos(4*pi/t6*epoch)+epoch*sin(6*pi/t6*epoch)+epoch*cos(6*pi/t6*epoch)+epoch*sin(8*pi/t6*epoch)+epoch*cos(8*pi/t6*epoch)+epoch*sin(10*pi/t6*epoch)+epoch*cos(10*pi/t6*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
      
     write(toString(lmX$coefficients), file = "mixedfullperiods_betas.txt", append=TRUE)
     write(toString(lmY$coefficients), file = "mixedfullperiods_betas.txt", append=TRUE)
     write(toString(lmZ$coefficients), file = "mixedfullperiods_betas.txt", append=TRUE)
     write(toString(lmVx$coefficients), file = "mixedfullperiods_betas.txt", append=TRUE)
     write(toString(lmVy$coefficients), file = "mixedfullperiods_betas.txt", append=TRUE)
     write(toString(lmVz$coefficients), file = "mixedfullperiods_betas.txt", append=TRUE)
}
```



