---
title: "R Notebook"
output: html_notebook
---


Llibraries
```{r}
library(readr)
library(car)
library(emmeans)
library(tables)
library(RcmdrMisc)
library(dplyr)
```

Dades
```{r}
#setwd("../../data")
dd <- read_csv("train.csv")

test <- read_csv("test.csv") # Canviar a test si es vol generar la submission (també s'ha de canviar el if del bucle)

test$epoch <- as.numeric(as.POSIXct(test$epoch))
dd$epoch <- as.numeric(as.POSIXct(dd$epoch))
test$epoch <- test$epoch - min(dd$epoch)
head(test)

dd$epoch <- dd$epoch - min(dd$epoch)
```

Models i prediccions
```{r}
for (i in unique(test$sat_id)){
  print(i)
 ddi <- filter(dd, sat_id==i)
 testi <- filter(test, sat_id==i)
 
  t1 <- TT[i+1,1]
  t2 <- TT[i+1,2]
  t3 <- TT[i+1,3]
  t4 <- TT[i+1,4]
  t5 <- TT[i+1,5]
  t6 <- TT[i+1,6]
  
  
 lmX <- lm(x ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmY <- lm(y ~ epoch+sin(2*pi/t2*epoch)+cos(2*pi/t2*epoch)+sin(4*pi/t2*epoch)+cos(4*pi/t2*epoch)+sin(6*pi/t2*epoch)+cos(6*pi/t2*epoch)+sin(8*pi/t2*epoch)+cos(8*pi/t2*epoch)+sin(10*pi/t2*epoch)+cos(10*pi/t2*epoch)+epoch*sin(2*pi/t2*epoch)+epoch*cos(2*pi/t2*epoch)+epoch*sin(4*pi/t2*epoch)+epoch*cos(4*pi/t2*epoch)+epoch*sin(6*pi/t2*epoch)+epoch*cos(6*pi/t2*epoch)+epoch*sin(8*pi/t2*epoch)+epoch*cos(8*pi/t2*epoch)+epoch*sin(10*pi/t2*epoch)+epoch*cos(10*pi/t2*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmZ <- lm(z ~ epoch+sin(2*pi/t3*epoch)+cos(2*pi/t3*epoch)+sin(4*pi/t3*epoch)+cos(4*pi/t3*epoch)+sin(6*pi/t3*epoch)+cos(6*pi/t3*epoch)+sin(8*pi/t3*epoch)+cos(8*pi/t3*epoch)+sin(10*pi/t3*epoch)+cos(10*pi/t3*epoch)+epoch*sin(2*pi/t3*epoch)+epoch*cos(2*pi/t3*epoch)+epoch*sin(4*pi/t3*epoch)+epoch*cos(4*pi/t3*epoch)+epoch*sin(6*pi/t3*epoch)+epoch*cos(6*pi/t3*epoch)+epoch*sin(8*pi/t3*epoch)+epoch*cos(8*pi/t3*epoch)+epoch*sin(10*pi/t3*epoch)+epoch*cos(10*pi/t3*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)

 lmVx <- lm(Vx ~ epoch+sin(2*pi/t4*epoch)+cos(2*pi/t4*epoch)+sin(4*pi/t4*epoch)+cos(4*pi/t4*epoch)+sin(6*pi/t4*epoch)+cos(6*pi/t4*epoch)+sin(8*pi/t4*epoch)+cos(8*pi/t4*epoch)+sin(10*pi/t4*epoch)+cos(10*pi/t4*epoch)+epoch*sin(2*pi/t4*epoch)+epoch*cos(2*pi/t4*epoch)+epoch*sin(4*pi/t4*epoch)+epoch*cos(4*pi/t4*epoch)+epoch*sin(6*pi/t4*epoch)+epoch*cos(6*pi/t4*epoch)+epoch*sin(8*pi/t4*epoch)+epoch*cos(8*pi/t4*epoch)+epoch*sin(10*pi/t4*epoch)+epoch*cos(10*pi/t4*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmVy <- lm(Vy ~ epoch+sin(2*pi/t5*epoch)+cos(2*pi/t5*epoch)+sin(4*pi/t5*epoch)+cos(4*pi/t5*epoch)+sin(6*pi/t5*epoch)+cos(6*pi/t5*epoch)+sin(8*pi/t5*epoch)+cos(8*pi/t5*epoch)+sin(10*pi/t5*epoch)+cos(10*pi/t5*epoch)+epoch*sin(2*pi/t5*epoch)+epoch*cos(2*pi/t5*epoch)+epoch*sin(4*pi/t5*epoch)+epoch*cos(4*pi/t5*epoch)+epoch*sin(6*pi/t5*epoch)+epoch*cos(6*pi/t5*epoch)+epoch*sin(8*pi/t5*epoch)+epoch*cos(8*pi/t5*epoch)+epoch*sin(10*pi/t5*epoch)+epoch*cos(10*pi/t5*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmVz <- lm(Vz ~ epoch+sin(2*pi/t6*epoch)+cos(2*pi/t6*epoch)+sin(4*pi/t6*epoch)+cos(4*pi/t6*epoch)+sin(6*pi/t6*epoch)+cos(6*pi/t6*epoch)+sin(8*pi/t6*epoch)+cos(8*pi/t6*epoch)+sin(10*pi/t6*epoch)+cos(10*pi/t6*epoch)+epoch*sin(2*pi/t6*epoch)+epoch*cos(2*pi/t6*epoch)+epoch*sin(4*pi/t6*epoch)+epoch*cos(4*pi/t6*epoch)+epoch*sin(6*pi/t6*epoch)+epoch*cos(6*pi/t6*epoch)+epoch*sin(8*pi/t6*epoch)+epoch*cos(8*pi/t6*epoch)+epoch*sin(10*pi/t6*epoch)+epoch*cos(10*pi/t6*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
  
 if (i == 1) {
  ans <- data.frame(id = testi$id, x=predict(lmX, testi), y=predict(lmY, testi), z=predict(lmZ, testi), Vx=predict(lmVx, testi), Vy=predict(lmVy, testi), Vz=predict(lmVz, testi))
 } else{
  ans <- rbind(ans, data.frame(id = testi$id, x=predict(lmX, testi), y=predict(lmY, testi), z=predict(lmZ, testi), Vx=predict(lmVx, testi), Vy=predict(lmVy, testi), Vz=predict(lmVz, testi)))
 }
}
```

Passar a csv
```{r}
ans$id <- format(ans$id, scientific = F)
ans$x <- format(ans$x, scientific = F)
ans$y <- format(ans$y, scientific = F)
ans$z <- format(ans$z, scientific = F)
ans$Vx <- format(ans$Vx, scientific = F)
ans$Vy <- format(ans$Vy, scientific = F)
ans$Vz <- format(ans$Vz, scientific = F)

write.csv(ans, "submission.csv", quote = F, row.names = F)
```


Calcul de les t
```{r}

TT <- matrix(1:3600, nrow=600)


for (i in 0:599){
   print(i)
   ddi <- filter(dd, sat_id==i)
   testi <- filter(test, sat_id==i)
   tt <- (ddi$epoch[25]-ddi$epoch[1])
  
  
   best_x <- 0
   best_y <- 0
   best_z <- 0
   best_Vx <- 0
   best_Vy <- 0
   best_Vz <- 0
   
   for (k in seq(0.95, 1.05, 0.001)) {
     t <- tt*k
    lmX <- lm(x ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
    
     lmY <- lm(y ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmZ <- lm(z ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)

 lmVx <- lm(Vx ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmVy <- lm(Vy ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
 
 lmVz <- lm(Vz ~ epoch+sin(2*pi/t*epoch)+cos(2*pi/t*epoch)+sin(4*pi/t*epoch)+cos(4*pi/t*epoch)+sin(6*pi/t*epoch)+cos(6*pi/t*epoch)+sin(8*pi/t*epoch)+cos(8*pi/t*epoch)+sin(10*pi/t*epoch)+cos(10*pi/t*epoch)+epoch*sin(2*pi/t*epoch)+epoch*cos(2*pi/t*epoch)+epoch*sin(4*pi/t*epoch)+epoch*cos(4*pi/t*epoch)+epoch*sin(6*pi/t*epoch)+epoch*cos(6*pi/t*epoch)+epoch*sin(8*pi/t*epoch)+epoch*cos(8*pi/t*epoch)+epoch*sin(10*pi/t*epoch)+epoch*cos(10*pi/t*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, ddi)
     
    if (summary(lmX)$adj.r.squared > best_x) {
      best_x <- summary(lmX)$adj.r.squared
      TT[i+1, 1] <- t
    }
   
    if (summary(lmY)$adj.r.squared > best_y) {
      best_y <- summary(lmY)$adj.r.squared
      TT[i+1, 2] <- t
    }
 
    if (summary(lmZ)$adj.r.squared > best_z) {
      best_z <- summary(lmZ)$adj.r.squared
      TT[i+1, 3] <- t
    }
 
    if (summary(lmVx)$adj.r.squared > best_Vx) {
      best_Vx <- summary(lmVx)$adj.r.squared
      TT[i+1, 4] <- t
    }
 
    if (summary(lmVy)$adj.r.squared > best_Vy) {
      best_Vy <- summary(lmVy)$adj.r.squared
      TT[i+1, 5] <- t
    }
 
    if (summary(lmVz)$adj.r.squared > best_Vz) {
      best_Vz <- summary(lmVz)$adj.r.squared
      TT[i+1, 6] <- t
    }
 
 }
   
   
   
   
}
```
Passar a csv
```{r}
write.csv(TT, "TT.csv", quote = F, row.names = F)
```
