---
title: "R Notebook"
output: html_notebook
---

Llibraries
```{r}
library(readr)
library(car)
library(emmeans)
library(tables)
library(RcmdrMisc)
library(dplyr)
```

Dades
```{r}
setwd("../../data")
train <- read_csv("train.csv")

test <- read_csv("test.csv") 

test$epoch <- as.numeric(as.POSIXct(test$epoch))
train$epoch <- as.numeric(as.POSIXct(train$epoch))

test$epoch <- test$epoch - min(train$epoch)
train$epoch <- train$epoch - min(train$epoch)

head(train)
head(test)
```

Las pruebas se haran sobre el 249
```{r}
ids <- 249
pr_train <- filter(train, sat_id == ids)
pr_test <- filter(test, sat_id == ids)
```


Corregir el plano
```{r}
a <- 1+75*24
b <- a+24
plot(pr_train$x[a:b], pr_train$y[a:b], type="l", col="blue")
```

Estimar la elipse
```{r}
TT <- read_csv("../../data/periods.csv")
tx <- unlist(TT[249+1,1])
ty <- unlist(TT[249+1,2])
```
```{r}
mod <- function(v){
  sqrt(v[1]*v[1]+v[2]*v[2]+v[3]*v[3])
}

vect_prod <- function(v1, v2){
  c(v1[2]*v2[3]-v1[3]*v2[2], v1[3]*v2[1]-v1[1]*v2[3], v1[1]*v2[2]-v1[2]*v2[1])
}

ang_vel <- function(dat) {
  ans <- c()
  for (i in 1:length(dat$epoch)){
    r <- c(dat$x[i], dat$y[i], 0)
    v <- c(dat$Vx[i], dat$Vy[i], 0)
    ans <- c(ans, mod(vect_prod(r, v)) / (mod(r)^2))
  }
  ans
}

a <- 1+10*24
b <- a+23

pr_train$w <- ang_vel(pr_train)*pr_train$epoch
plot(pr_train$epoch, ang_vel(pr_train), type="l")

lmX <- lm(x ~ sin(w)+cos(w), data = pr_train[a:b,])
lmY <- lm(y ~ sin(w)+cos(w), data = pr_train[a:b,])
  
plot(predict(lmX), predict(lmY), col="blue")
points(pr_train$x[a:b], pr_train$y[a:b])
```
```{r}
n_elipses <- function(dat, a, b, n, pred=T, test) {
  delta <- 4
  bi <- a-1
  for (i in 1:n) {
      ai <- bi+1
      bi <- ai+delta-1
      if (i == n) {
        bi <- b
      }
      tx <- 6 * (pr_train$epoch[bi]-pr_train$epoch[ai])
      ty <- tx
        
      lmX <- lm(x ~ sin(2*pi*epoch/tx)+cos(2*pi*epoch/tx), data = dat[ai:bi,])
      lmY <- lm(y ~ sin(2*pi*epoch/ty)+cos(2*pi*epoch/ty), data = dat[ai:bi,])
      
      coefX <- lmX$coefficients
      coefY <- lmY$coefficients
      if (i == 1) {
        ans <- data.frame(x=predict(lmX, test[ai:bi,]), y=predict(lmY, test[ai:bi,]))
        coefs <- data.frame(ax=coefX[1], ax=coefX[1], bx=coefX[2], cx=coefX[3], by=coefY[2], cy=coefY[3])
      } else {
        ans <- rbind(ans, data.frame(x=predict(lmX, test[ai:bi,]), y=predict(lmY, test[ai:bi,])))
        coefs <- rbind(coefs, data.frame(ax=coefX[1], ax=coefX[1], bx=coefX[2], cx=coefX[3], by=coefY[2], cy=coefY[3]))
      }
  }
  if (pred) {ans}
  else {coefs} 
}

a <- 1+0*24
b <- a+23+0*24

pred <- n_elipses(pr_train, a, b, as.integer((b-a+1)/4), test=pr_train)
plot(pr_train$x[a:b], pr_train$y[a:b])
points(pred$x, pred$y, col="blue")
```
```{r}
dd <- pr_train
dd$x_sim <- pred[c(rep(seq_len(nrow(pred)), 76),1:12), ]$x
dd$y_sim <- pred[c(rep(seq_len(nrow(pred)), 76),1:12), ]$y
dd$id <- (as.double(dd$id)-469143)/24

cambioX <- lm(x ~ epoch*sin(2*pi*epoch/tx)+epoch*cos(2*pi*epoch/tx) + x_sim + y_sim , data = dd)
cambioY <- lm(y ~ epoch*sin(2*pi*epoch/ty)+epoch*cos(2*pi*epoch/ty) + x_sim + y_sim , data = dd)

plot(dd$x, dd$y, type="l")
lines(dd$x_sim, dd$y_sim, col ="blue")
lines(predict(cambioX), predict(cambioY), col="red")
```

Predecir
```{r}

```

Contra-corregir el plano
```{r}

```

Pasar a csv para visualizar
```{r}
no_scientific <- function(ans, sim=F) {
  ans$id <- format(ans$id, scientific = F)
  ans$x <- format(ans$x, scientific = F)
  ans$y <- format(ans$y, scientific = F)
  ans$z <- format(ans$z, scientific = F)
  ans$Vx <- format(ans$Vx, scientific = F)
  ans$Vy <- format(ans$Vy, scientific = F)
  ans$Vz <- format(ans$Vz, scientific = F)
  
  if (sim) {
    ans$x_sim <- format(ans$x_sim, scientific = F)
    ans$y_sim <- format(ans$y_sim, scientific = F)
    ans$z_sim <- format(ans$z_sim, scientific = F)
    ans$Vx_sim <- format(ans$Vx_sim, scientific = F)
    ans$Vy_sim <- format(ans$Vy_sim, scientific = F)
    ans$Vz_sim <- format(ans$Vz_sim, scientific = F)
  }
  ans
}

output_train <- no_scientific(pr_train, T)
output_test <- no_scientific(pr_test, F)
output_test$x <- pred$x
output_test$y <- pred$y
output_test$z <- pred$y
write_csv(output_train, "train.csv", quote=F)
write_csv(output_test, "test.csv", quote=F)
```














