---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(car)
```

```{r}
train <- read_csv("../../data/train.csv")
test <- read_csv("../../data/test.csv")

test$epoch <- as.numeric(as.POSIXct(test$epoch))
train$epoch <- as.numeric(as.POSIXct(train$epoch))
test$epoch <- test$epoch - min(train$epoch)
train$epoch <- train$epoch - min(train$epoch)

TT <- read_csv("../../data/periods.csv")
```

Score
```{r}
score <- function(val_pred, val_real) {
  smape <- mean(abs(val_pred - val_real) / (abs(val_pred)+abs(val_real)))
  100 * (1 - smape)
}
```

Models
```{r}
model <- function(sat, coord, num_model, pred=F) {
  #print(c(sat, coord, num_model, pred, " ???"))
  
  t1 <- unlist(TT[sat+1,coord])
  if (!pred) {
    tr <- train %>% filter(sat_id == sat)
  
    total <- length(tr$epoch)
    limit <- as.integer(0.8 * total)
    
    val <- tr[limit:total,]
    tr <- tr[1:(limit-1),]
    tr2 <- tr[as.integer(length(tr$id)*0.1):length(tr$id),]
    
    tr$aux <- unlist(tr[,coord+3])
    tr2$aux <- unlist(tr2[,coord+3])
    val$aux <- unlist(val[,coord+3])
  } else {
    tr <- train %>% filter(sat_id == sat)
    tst <- test %>% filter(sat_id == sat)
    tr2 <- tr[as.integer(length(tr$id)*0.1):length(tr$id),]
    
    tr$aux <- unlist(tr[,coord+3])
    tst$aux <- unlist(tst[,coord+3])
    tr2$aux <- unlist(tr2[,coord+3])
    
    
  }
  
  #modelos iniciales
          if (num_model == 1) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr)
    } else if (num_model == 2) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch), tr)
    } else if (num_model == 3) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr)
    } else if (num_model == 4) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr)
    } else if (num_model == 5) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch), tr)
    } 
  
  
  #con tr2
  #modelo lineal
  else if (num_model == 6) {
        lmX <- lm(aux ~ x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
  }
  
  #3 armónicos
      else if (num_model == 7) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 8) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch), tr2)
    } else if (num_model == 9) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr2)
    } else if (num_model == 10) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 11) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch), tr2)
    }
  
  #4 armónicos
      else if (num_model == 12) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 13) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch), tr2)
    } else if (num_model == 14) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr2)
    } else if (num_model == 15) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 16) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch), tr2)
    }
    
  #5 armónicos
      else if (num_model == 17) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 18) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch), tr2)
    } else if (num_model == 19) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr2)
    } else if (num_model == 20) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 21) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch), tr2)
    }
  
  #6 armónicos
      else if (num_model == 22) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 23) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch), tr2)
    } else if (num_model == 24) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr2)
    } else if (num_model == 25) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 26) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch), tr2)
    }
  
  #7 armónicos
      else if (num_model == 27) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 28) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch), tr2)
    } else if (num_model == 29) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr2)
    } else if (num_model == 30) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+sin(14*pi/t1*epoch)+cos(14*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 31) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+sin(14*pi/t1*epoch)+cos(14*pi/t1*epoch), tr2)
    }
  
  #8 armónicos
      else if (num_model == 32) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 33) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch), tr2)
    } else if (num_model == 34) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr2)
    } else if (num_model == 35) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+sin(14*pi/t1*epoch)+cos(14*pi/t1*epoch)+sin(16*pi/t1*epoch)+cos(16*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 36) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+sin(14*pi/t1*epoch)+cos(14*pi/t1*epoch)+sin(16*pi/t1*epoch)+cos(16*pi/t1*epoch), tr2)
    }
  
  #9 armónios
      else if (num_model == 37) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch)+epoch*sin(18*pi/t1*epoch)+epoch*cos(18*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 38) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch)+epoch*sin(18*pi/t1*epoch)+epoch*cos(18*pi/t1*epoch), tr2)
    } else if (num_model == 39) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch)+epoch*sin(18*pi/t1*epoch)+epoch*cos(18*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr2)
    } else if (num_model == 40) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+sin(14*pi/t1*epoch)+cos(14*pi/t1*epoch)+sin(16*pi/t1*epoch)+cos(16*pi/t1*epoch)+sin(18*pi/t1*epoch)+cos(18*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 41) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+sin(14*pi/t1*epoch)+cos(14*pi/t1*epoch)+sin(16*pi/t1*epoch)+cos(16*pi/t1*epoch)+sin(18*pi/t1*epoch)+cos(18*pi/t1*epoch), tr2)
    }
  
  #10 armónicos
      else if (num_model == 42) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch)+epoch*sin(18*pi/t1*epoch)+epoch*cos(18*pi/t1*epoch)+epoch*sin(20*pi/t1*epoch)+epoch*cos(20*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 43) {
        lmX <- lm(aux ~ epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+epoch*sin(4*pi/t1*epoch)+epoch*cos(4*pi/t1*epoch)+epoch*sin(6*pi/t1*epoch)+epoch*cos(6*pi/t1*epoch)+epoch*sin(8*pi/t1*epoch)+epoch*cos(8*pi/t1*epoch)+epoch*sin(10*pi/t1*epoch)+epoch*cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch)+epoch*sin(18*pi/t1*epoch)+epoch*cos(18*pi/t1*epoch)+epoch*sin(20*pi/t1*epoch)+epoch*cos(20*pi/t1*epoch), tr2)
    } else if (num_model == 44) {
        lmX <- lm(aux ~ epoch+epoch*sin(2*pi/t1*epoch)+epoch*cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+epoch*sin(12*pi/t1*epoch)+epoch*cos(12*pi/t1*epoch)+epoch*sin(14*pi/t1*epoch)+epoch*cos(14*pi/t1*epoch)+epoch*sin(16*pi/t1*epoch)+epoch*cos(16*pi/t1*epoch)+epoch*sin(18*pi/t1*epoch)+epoch*cos(18*pi/t1*epoch)+epoch*sin(20*pi/t1*epoch)+epoch*cos(20*pi/t1*epoch)+epoch*x_sim+epoch*y_sim+epoch*z_sim+epoch*Vx_sim+epoch*Vy_sim+epoch*Vz_sim, tr2)
    } else if (num_model == 45) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+sin(14*pi/t1*epoch)+cos(14*pi/t1*epoch)+sin(16*pi/t1*epoch)+cos(16*pi/t1*epoch)+sin(18*pi/t1*epoch)+cos(18*pi/t1*epoch)+sin(20*pi/t1*epoch)+cos(20*pi/t1*epoch)+x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, tr2)
    } else if (num_model == 46) {
        lmX <- lm(aux ~ epoch+sin(2*pi/t1*epoch)+cos(2*pi/t1*epoch)+sin(4*pi/t1*epoch)+cos(4*pi/t1*epoch)+sin(6*pi/t1*epoch)+cos(6*pi/t1*epoch)+sin(8*pi/t1*epoch)+cos(8*pi/t1*epoch)+sin(10*pi/t1*epoch)+cos(10*pi/t1*epoch)+sin(12*pi/t1*epoch)+cos(12*pi/t1*epoch)+sin(14*pi/t1*epoch)+cos(14*pi/t1*epoch)+sin(16*pi/t1*epoch)+cos(16*pi/t1*epoch)+sin(18*pi/t1*epoch)+cos(18*pi/t1*epoch)+sin(20*pi/t1*epoch)+cos(20*pi/t1*epoch), tr2)
    }
  
  
  #print(summary(lmX))
  
  if (num_model < 47){ #Modelo predicho = simulado
    if (!pred) score(predict(lmX, val), unlist(val[,coord+3]))
    else predict(lmX, tst)
  }
  else {
    if (!pred) score(unlist(val[,coord+9]), unlist(val[,coord+3]))
    else unlist(tst[,coord+3])
  }
}
```


```{r}
last
```

```{r}
sat <- 37
coord <- 6
model(sat, coord, ans[sat+1,coord+1])
model(sat, coord, 6)
```

Cases
```{r}
last <- read_csv("cases3.csv")

frequencies <- integer(18)

for (i in 0:599) {
  print(i)
  mods <- data.frame(sat_id=i,x=0,y=0,z=0,Vx=0,Vy=0,Vz=0)
  for (coo in 1:6) {
    mx <- 0
    for (mod in c(last[i+1,coo+1], 6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47)) {
      sc <- model(i, coo, mod)
      if (sc > mx) {
        mx <- sc
        best <- mod
      }
    }
    
    #frequencies[best-5] <- frequencies[best-5] + 1 
    
    mods[,coo+1] <- best
    if (best != last[i+1,coo+1] & i %in% unique(test$sat_id)) {
     print(sprintf("Satelite: %i, coord: %i, ha camiado al modelo: %i", i,coo,best))
    }
  }
  if (i == 0) ans <- mods
  else ans <- rbind(ans, mods)
}
write_csv(ans, "cases4.csv", quote=F)

print(frequencies)
```



```{r}
ans <- read_csv("cases4.csv")
print(ans)

```


```{r}
i <- 1
ddi <- filter(test, sat_id==i)
coor <- 1

PR <- model(i, coor, ans[i+1, coor+1], T)
head(PR)
  
plot(ddi$epoch, unlist(predict(PR, ddi)), main= toString(i))
points(ddi$epoch, ddi$x, col = "blue")
```


Predict
```{r}
for (i in unique(test$sat_id)) {
  print(i)
  pred <- filter(test, sat_id==i)
  for (coor in 1:6) {
    pred[,coor+3] <- model(i, coor, ans[i+1, coor+1], T)
  }
  
  if (i == unique(test$sat_id)[1]) sol <- data.frame(id=pred$id, x=unlist(pred[,1+3]), y=unlist(pred[,2+3]), z=unlist(pred[,3+3]), Vx=unlist(pred[,4+3]), Vy=unlist(pred[,5+3]), Vz=unlist(pred[,6+3]))
  else sol <- rbind(sol, data.frame(id=pred$id, x=unlist(pred[,1+3]), y=unlist(pred[,2+3]), z=unlist(pred[,3+3]), Vx=unlist(pred[,4+3]), Vy=unlist(pred[,5+3]), Vz=unlist(pred[,6+3])))
}
```



```{r}
write_csv(sol, "Submission.csv", quote=F)
```




Frequencies of the models 
```{r}

freq <- integer(47)

for (i in 0:599) {
    for (cor in 0:6){
        freq[unlist(ans[i+1, coor+1])] <- freq[unlist(ans[i+1, coor+1])] + 1 
    } 
}

print(freq)
```







