---
title: "Polinomio"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Read data
```{r}
library(readr)
library(car)
library(emmeans)
library(tables)
library(RcmdrMisc)
library(dplyr)


dd <- read_csv("train.csv")
dd$dist <- sqrt(dd$x^2 + dd$y^2 + dd$z^2)
dd$epoch <- as.numeric(as.POSIXct(dd$epoch))
dd$epoch <- dd$epoch - min(dd$epoch)
head(dd)

test <- read_csv("test.csv")
test$epoch <- as.numeric(as.POSIXct(test$epoch))
test$epoch <- test$epoch - min(test$epoch)
head(test)
```

# Regression by polinomial
```{r}
a = 1
b = 24*2
dd0 <- dd %>% filter(sat_id==0)
dd0 <- dd0[a:b,]

deg <- glm(x ~ poly(epoch, 20, raw=T), data = dd0, family=gaussian())

Anova(deg)
plot(dd0$epoch, predict(deg), col = "red")
points(dd0$epoch, dd0$x)
```

```{r}
aa <- 1
bb <- 500

dd02 <- (dd %>% filter(sat_id==0))[aa:bb,]
nd <- dd02
nd$epoch <- nd$epoch %% (67272.0119130404*2)

plot(dd02$epoch, dd02$x)
points(dd02$epoch, predict.glm(deg, newdata=nd), col = "red")
#points(dd02$epoch, dd02$x_sim, col = "green")
```
```{r}
lmX <- lm(x ~ x_sim+y_sim+z_sim+Vx_sim+Vy_sim+Vz_sim, dd%>%filter(sat_id==0))
plot(dd02$epoch, dd02$x)
points(dd02$epoch, predict.lm(lmX, newdata=dd02), col = "red")
```

# SISTEMATIZACION
```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

period <- function(t, s, cut){
  m <- which.min(s)
  mins = c()
  for(j in 1:length(s)){
      if (abs(s[j]-s[m]) < cut){
        mins <- c(mins, j)
      }
  }
  
  per1 <- c()
  per2 <- c()
  for(j in 2:length(mins)){
    per1 <- c(per1, t[mins[j]]-t[mins[j-1]])
    per2 <- c(per2, mins[j]-mins[j-1])
  }
  
  T_sec <- mean(per1)
  T_samples <- getmode(per2)
  c(T_samples, T_sec)
}
```


```{r}
ans <- c()
for(i in 0:2){
  ddi <- filter(dd, sat_id==i)
  testi <- filter(test, sat_id==i)
  
  (aux <- period(ddi$epoch, ddi$x, 100))
  T_samples <- as.integer(aux[1])
  T_sec <- aux[2]
  ddx <- ddi[ddi$id[1]:(ddi$id[1]+2*T_samples),]
  degx <- glm(x ~ poly(epoch, 20, raw=T), data = ddx, family=gaussian())
  ndx <- testi
  ndx$epoch <- ndx$epoch %% (T_sec*2)
  
  (aux <- period(ddi$epoch, ddi$y, 100))
  T_samples <- as.integer(aux[1])
  T_sec <- aux[2]
  ddy <- ddi[ddi$id[1]:(ddi$id[1]+2*T_samples),]
  degy <- glm(y ~ poly(epoch, 20, raw=T), data = ddy, family=gaussian())
  ndy <- testi
  ndy$epoch <- ndy$epoch %% (T_sec*2)
  
  (aux <- period(ddi$epoch, ddi$z, 100))
  T_samples <- as.integer(aux[1])
  T_sec <- aux[2]
  ddz <- ddi[ddi$id[1]:(ddi$id[1]+2*T_samples),]
  degz <- glm(z ~ poly(epoch, 20, raw=T), data = ddz, family=gaussian())
  ndz <- testi
  ndz$epoch <- ndz$epoch %% (T_sec*2)
  
  (aux <- period(ddi$epoch, ddi$Vx, 0.01))
  T_samples <- as.integer(aux[1])
  T_sec <- aux[2]
  ddVx <- ddi[ddi$id[1]:(ddi$id[1]+2*T_samples),]
  degVx <- glm(Vx ~ poly(epoch, 20, raw=T), data = ddVx, family=gaussian())
  ndVx <- testi
  ndVx$epoch <- ndVx$epoch %% (T_sec*2)
  
  aux <- period(ddi$epoch, ddi$Vy, 0.01)
  T_samples <- as.integer(aux[1])
  T_sec <- aux[2]
  ddVy <- ddi[ddi$id[1]:(ddi$id[1]+2*T_samples),]
  degVy <- glm(Vy ~ poly(epoch, 20, raw=T), data = ddVy, family=gaussian())
  ndVy <- testi
  ndVy$epoch <- ndVy$epoch %% (T_sec*2)
  
  aux <- period(ddi$epoch, ddi$Vz, 0.01)
  T_samples <- as.integer(aux[1])
  T_sec <- aux[2]
  ddVz <- ddi[ddi$id[1]:(ddi$id[1]+2*T_samples),]
  degVz <- glm(Vz ~ poly(epoch, 20, raw=T), data = ddVz, family=gaussian())
  ndVz <- testi
  ndVz$epoch <- ndVz$epoch %% (T_sec*2)
  
   if (i == 1) {
    ans <- data.frame(id = testi$id, x=predict(degx, ndx), y=predict(degy, ndy), z=predict(degz, ndz), Vx=predict(degVx, ndVx), Vy=predict(degVy, ndVy), Vz=predict(degVz, ndVz))
   } else {
    ans <- rbind(ans, data.frame(id = testi$id, x=predict(degx, ndx), y=predict(degy, ndy), z=predict(degz, ndz), Vx=predict(degVx, ndVx), Vy=predict(degVy, ndVy), Vz=predict(degVz, ndVz)))
 }
}

ans$id <- format(ans$id, scientific = F)
ans$x <- format(ans$x, scientific = F)
ans$y <- format(ans$y, scientific = F)
ans$z <- format(ans$z, scientific = F)
ans$Vx <- format(ans$Vx, scientific = F)
ans$Vy <- format(ans$Vy, scientific = F)
ans$Vz <- format(ans$Vz, scientific = F)

write.csv(ans, "submission.csv", quote = F, row.names = F)
```





